DepotApp/DepotApp/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TiendaDepot.urls')),
    path('carro/', include('carro.urls')),
]

DepotApp/TiendaDepot/urls.py
from django.urls import path
from TiendaDepot import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name="Index"),
    path('\popu', views.indexPopu, name="IndexPopu"),
    path('\promo', views.indexPromo, name="IndexPromo"),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DepotApp/carro/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path('', views.carrito, name='carrito'),
    path('agregar/<int:articulo_id>/', views.agregar_articulo, name="agregar"),
    path('restar/<int:articulo_id>/', views.restar_articulo, name="restar"),
    path('okpedido', views.okPedido, name="okPedido"),
]

DepotApp/TiendaDepot/models.py
from django.db import models

# Create your models here.
class Articulo(models.Model):
    Nombre=models.CharField(max_length=50)
    imagen=models.ImageField(upload_to="TiendaDepot",null=True, blank=True)
    precio=models.FloatField()
    stock=models.IntegerField()
    TIPO_ARTICULO_CHOICES = [
        (1,'Normal'),
        (2,'Popular'),
        (3,'Promo'),
    ]
    tipo=models.IntegerField(choices=TIPO_ARTICULO_CHOICES, default=1)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='Articulo'
        verbose_name_plural='Articulos'

    def __str__(self):
        return self.Nombre


class Pedido(models.Model):
    Usuario=models.CharField(max_length=50)
    NombreArticulo=models.CharField(max_length=50)
    Precio=models.FloatField()
    Cantidad=models.IntegerField()
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name= 'Pedido'
        verbose_name_plural='Pedidos'
    
def __str__(self):
    return self.Usuario+ " "+self.NombreArticulo

DepotApp/carro/models.py
from django.db import models

# Create your models here.

DepotApp/TiendaDepot/views.py
from django.shortcuts import render
from TiendaDepot.models import Articulo

def index(request):
    Articulos=Articulo.objects.all().order_by("Nombre")
    return render (request, "index.html", {"articulos":Articulos})

def indexPopu(request):
    articulos=Articulo.objects.all().filter(tipo__contains=2).order_by("Nombre")
    return render (request, "index.html", {"articulos":articulos})
    
def indexPromo(request):
    articulos=Articulo.objects.all().filter(tipo__contains=3).order_by("Nombre")
    return render (request, "index.html", {"articulos":articulos})
    

DepotApp/carro/views.py
from django.shortcuts import render,redirect
from .carro import carro
from TiendaDepot.models import Articulo, Pedido

def agregar_articulo(request,articulo_id):
    Carro = carro(request)
    articulo = Articulo.objects.get(id=articulo_id)
    Carro.agregar(articulo)
    return redirect("Index")

def restar_articulo(request,articulo_id):
    Carro = carro(request)
    articulo = Articulo.objects.get(id=articulo_id)
    Carro.restar(articulo)
    return redirect("Index")

def limpiar_carro(request):
    Carro = carro(request)
    Carro.limpiarCarro()
    return redirect("Index")

def carrito(request):
    return render (request, "carro.html")

def okPedido(request):
    if request.user.is_authenticated:

        for key, value in request.session["carro"].items():
            usuario=request.user
            nombreArticulo=value["nombre"]
            precio=value["precio"]
            cantidad=value["cantidad"]
            pedido= Pedido.objects.create(Usuario=usuario, NombreArticulo=nombreArticulo, Precio=precio, Cantidad=cantidad)
        limpiar_carro(request)
        return render (request,"pedido.html")
    else:
        return render (request, "autenticar.html")

DepotApp/TiendaDepot/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <script src="{% static 'JS/scripts.js' %}"></script>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DepotApp</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logos/favicon.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Index' %}"><img src="{% static 'assets/img/logos/logo2.png' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                  
                        <li class="nav-item"><a class="nav-link" href="{% url 'Index' %}">Articulos</a></li>
                     
                        <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'carro:carrito' %}">Carro</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'IndexPopu' %}">Populares</a></li>
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'IndexPromo' %}">Promocion</a></li>
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">BIENVENIDOS a DEPOTAPP</div>
                <div class="masthead-heading text-uppercase">Aplicacion de deposito</div>
                <a class="btn btn-primary btn-xl text-uppercase" href="#portfolio">Vea nuestros Articulos</a>
            </div>
        </header>
        
        <!-- Portfolio Grid-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Articulos</h2>
                    <h3 class="section-subheading text-muted">El mejor lugar sin lugar a dudas</h3>
                </div>
            <section class="py-5" >
                <div class="container px-4 pxlg-5 mt-5">
                    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for articulo in articulos %}
                    <div class="col mb-5">
                        <div class="card h-100" >
                            {% if articulo.tipo == 3 %}
                                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem ">
                                    PROMO !
                                </div>

                            {% endif %}
                  
                                <img class="card-img-top" src="{{articulo.imagen.url}}" alt="..." />
                                <div class="card-body p-4">
                                    <div class="text-center" >
                                       
                                    <h5 class="fw-bolder">{{articulo.Nombre}}</h5>
                                  

                                    <p>PRECIO:  {{articulo.precio}}</p>
                                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'carro:agregar' articulo.id %}">Agregar al carro</a></div>
                                    </div>
                                    {% if articulo.tipo == 2 %}
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                           
                        </div>
                    </div>
                {% endfor %}
                    </div>
                </div>
            </section>       


        <!-- Team-->
        <section class="page-section bg-light" id="team">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Nuestro equipo de trabajo</h2>
                    <h3 class="section-subheading text-muted">Representamos Depot App en todo Neuquen</h3>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/1.jpg' %}" alt="..." />
                            <h4>Martin Lacabanne</h4>
                            <p class="text-muted">Se fue a Buenos Aires a programar y desaparecio</p>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/3.jpg' %}" alt="..." />
                            <h4>Santiago Imas</h4>
                            <p class="text-muted">Te comenta el codigo</p>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Twitter Profile"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/3.jpg' %}" alt="..." />
                            <h4>Ignacio Otarola</h4>
                            <p class="text-muted">No hizo nada pero esta a Disposicion</p>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Twitter Profile"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">En este equipo sobran las ganas y la predisposicion de cada uno, no ponemos la cabeza, ponemos el corazon</p></div>
                </div>
            </div>
        </section>
       
                    
        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; DEPOTAPP 2022</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                  
                </div>
            </div>
        </footer>

        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

DepotApp/carro/templates/autenticar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <script src="{% static 'JS/scripts.js' %}"></script>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DepotApp</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logos/favicon.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Index' %}"><img src="{% static 'assets/img/logos/logo2.png' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                  
                        <li class="nav-item"><a class="nav-link" href="{% url 'Index' %}">Articulos</a></li>
                     
                        <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'carro:carrito' %}">Carro</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'IndexPopu' %}">Populares</a></li>
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'IndexPromo' %}">Promocion</a></li>
                        
                    </ul>
                </div>
            </div>
        </nav>

        <div class="d-grid gap-2 col-4 mx-auto py-2">
            <h4 class="display-7 text-center">Ingresar a tu cuenta para confirmar pedido</h4>
            <a href="#" class="btn btn-primary btn-sm">Crear CUENTA</a>
            <a href="#" class="btn btn-outline-primary btn-sm">INGRESAR</a>
        </div>

DepotApp/carro/templates/carro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <script src="{% static 'JS/scripts.js' %}"></script>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DepotApp</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logos/favicon.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Index' %}"><img src="{% static 'assets/img/logos/logo2.png' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                  
                        <li class="nav-item"><a class="nav-link" href="{% url 'Index' %}">Articulos</a></li>
                     
                        <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'carro:carrito' %}">Carro</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'IndexPopu' %}">Populares</a></li>
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'IndexPromo' %}">Promocion</a></li>
                        
                    </ul>
                </div>
            </div>
        </nav>

    <body>

        <header class="bg-warning py-1">
            <div class="container px-4 px-lg-5 my-1">
                <div class="text-center text-black">
                    <h1 class="display-6 fw-bolder">Detalle del Carrito</h1>

                </div>

            </div>
        </header>

        <section>
            <div class="container px-4 px-lg-5 mt-2">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3">
                    {% for key, value in request.session.carro.items %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <img class="card-img-top" src="{{value.imagen}}" alt="..." />

                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <h5 class="fw-bolder">{{value.nombre}}</h5>
                                        <div>
                                            {% if value.cantidad > 1 %}
                                                {{value.cantidad}} unidades
                                            {% else %}
                                                {{value.cantidad}} unidad
                                            {% endif %}
                                        </div>
                                        <div>
                                            Total ${{value.precio}}
                                        </div>
                                    </div>

                                </div>

                            </div>
                                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                       <div class="text-center">
                                        <a href="{% url 'carro:restar' value.articulo_id %}"
                                            class="btn btn-success mt-auto">Quitar una unidad
                                        </a>
                                       </div> 
                                    </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </section>

        <div class="d-grid gap-2 col-4 mx-auto py-2">
            <a href="{% url 'carro:okPedido' %}" class="btn btn-primary">REALIZAR PEDIDO</a>

        </div>


        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; DEPOTAPP 2022</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                  
                </div>
            </div>
        </footer>

        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'static/JS/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 

    </body>
</html>

DepotApp/carro/templates/pedido.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <script src="{% static 'JS/scripts.js' %}"></script>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DepotApp</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logos/favicon.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->

            <div class="d-grid gap-2 col-4 mx-auto py-2">
                <h4 class="display-7 text-center fw-bolder">PEDIDO REALIZADO</h4>
                <a href="{% url 'Index' %}" class="btn btn-primary">VOLVER</a>
            </div>
       